name: Discussions To Blog
description: Pull specific category posts from GitHub Discussions and generate Markdown files
author: zhanyeye

inputs:
  categories:
    description: "The categories in GitHub Discussions to be converted into blog posts, format: xxx1, xxx2, xxx3"
    required: true
  output_dir:
    description: "The output directory for generated files"
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: 'book'
  color: 'yellow'