name: Discussions To Blog
description: 从 GitHub Discussions 中拉取指定 Category 帖子，并生成 Markdown 文件
author: zhanyeye

inputs:
  categories:
    description: "Discussions 中确定需要转blog 的 category, 格式 xxx1, xxxx2, xxx3"
    required: true
  output_dir:
    description: "输出路径"
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: 'book'
  color: 'yellow'